<?php

namespace CoreBundle\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRango($rango)
	{
	
		try {
	
			$sql = 'SELECT m FROM CoreBundle:Menu m';
				
			$sql .= ' WHERE m.dia >= :startDay AND m.dia <= :endDay ORDER BY m.dia ASC ';
			
			$query = $this->getEntityManager()
			->createQuery($sql)
            ->setParameter('startDay', $rango['startDay'])
            ->setParameter('endDay', $rango['endDay'])
			;
            
			$menues = $query->getResult();
	
			if($menues) {
				return $menues;
			} else {
				return array();
			}
				
	
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	
	}

	public function findForMarket($cliente)
	{
	
		try {
	
			$sql = 'SELECT m FROM CoreBundle:Menu m';
				
			$sql .= ' WHERE m.cliente =:cliente ORDER BY m.modificacionFecha DESC ';
			
			$query = $this->getEntityManager()
			->createQuery($sql)
			->setParameter('cliente', $cliente)
			->setMaxResults(1)
			;
            
			$menues = $query->getResult();
	
			if($menues) {
				return $menues;
			} else {
				return array();
			}
				
	
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	
	}
}
