<?php

namespace CoreBundle\Repository;

/**
 * PedidoItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoItemRepository extends \Doctrine\ORM\EntityRepository
{
}
