<?php

namespace CoreBundle\Repository;

/**
 * PeriodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodoRepository extends \Doctrine\ORM\EntityRepository
{
}
