<?php

namespace CoreBundle\Repository;

/**
 * PlatoMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatoMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
