<?php

namespace CoreBundle\Repository;

/**
 * PlatosDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatosDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
